### ISSUE TITLE
Sixpack is not built, but copied

### ISSUE THREAD

**Issue by clbr** [kubilus1/gendev#10]
The sixpack program is just copied. This is an issue, because it's 32-bit, and I'm on a 64-bit system. I could also be on non-x86, etc, and sixpack sources are included, so it makes sense it should be built.

**Comment by clbr** [comment]
After taking a closer look, this is pretty bad. It depends on several unknown libraries, has missing source files, and neither it nor the libraries I found have any build systems.

Having such a low-quality program included, as a binary-only way too which is a security issue, is certainly unadvisable.

**Comment by kubilus1** [comment]
Yeah, I agree with you about sixpack not being great.  I looked into compiling this at one point, which is next to impossible.  Not sure I agree that because it is a binary means it's necessarily a security risk though.   I _think_ I can drop it, let me check.

**Comment by doragasu** [comment]
I found also this issue about a year ago, when I was trying to build the toolchain on an ARM Chromebook (obviously x86 binaries do not run on ARM).

I traced the problem down to missing aPLib, and found aPLib sources: http://ibsensoftware.com/download.html

Unfortunately for me, some functions are x86 assembly, and I do not have the time and motivation to translate them to C or ARM assembly, so I left it there.

I have never written x86_64 assembly, so I don't know the changes needed (if any) to the assembly sources to build them for x86_64, but I suppose it shouldn't be too difficult though...

**Comment by clbr** [comment]
Those are the decompression sources. aplib compression is closed source.

**Comment by doragasu** [comment]
I had again a look to the sources, and you are right, compression routines are closed. I suppose I noticed this when I was trying to build sixpack a year ago, but I completely forgot about it.

**Comment by kubilus1** [comment]
Unless there are improvements for the piece of software, I will close this issue as not fixable.

**Comment by clbr** [comment]
The proper fix would be not to use sixpack.
