### ISSUE TITLE
sega.s needs to be updated

### ISSUE THREAD

**Issue by clbr** [kubilus1/gendev#11]
The latest toolchain requires an updated sega.s to function. Anyone using the current gendev will produce broken binaries.

**Comment by nevat** [comment]
Same problem here. A simple "Hello World" don't work (nothing showed on screen, or some strange behaviour).

**Comment by kubilus1** [comment]
Okay, I've synced this up with the latest sega.s.  This should work now!

**Comment by clbr** [comment]
Wrt the cleanup in the same commit: you should use "git clean -fdx" to remove all non-tracked files. rm -rf means wasted bandwidth as it has to be re-cloned each time then.
