### ISSUE TITLE
Rom compilation failed.

### ISSUE THREAD

**Issue by Gmontserrat** [kubilus1/gendev#12]
Hi, i've tried to use gendev to compile the hello world example under linux (debian and mint) but i only get a rom file that gives me a black screen. The windows version using codeblocks worked fine btw.

I've started a post in spriteminds asking for help, there are the terminal logs. Could you help me undestand how to use it? its posible to use codeblocks or any other ide?

http://gendev.spritesmind.net/forum/viewtopic.php?f=19&t=2304

**Comment by kubilus1** [comment]
I believe those was resolved in the posted link.  Closing.
