### ISSUE TITLE
Object and elf files are deleted after build

### ISSUE THREAD

**Issue by doragasu** [kubilus1/gendev#13]
I don't know why, but each time I build a project, after building, the intermediate object files and the elf file, are deleted, just after the the output binary padding. It always looks like this (notice the last line doing the rm):

```
dd if=temp.bin of=out.bin bs=8K conv=sync
8+1 records in
9+0 records out
73728 bytes (74 kB) copied, 0.000230092 s, 320 MB/s
rm mw/module1.o main.o mw/module2.o out.elf
```

I had a look to the Makefile, and it's a mystery for me why these files are deleted, as the only places in which $(RM) is invoked, don't look like to be the ones that are deleting these files.

I do not want these files to be deleted, as sometimes I examine them (e.g. disassemble using objdump), but I have no clue why they are deleted.

**Comment by kubilus1** [comment]
That's standard Make stuff.  Intermediate files such as .elf .o are deleted by default.  There are probably switches you can send to make to prevent this.

**Comment by doragasu** [comment]
Didn't know about "intermediate files" in makefiles (and my own produced simple makefiles never automatically delete object files). I have been reading a bit, and got the files to persist by adding to the makefile:

```
.SECONDARY: $(RESOURCES) out.elf
```

Thanks for the tip!

BTW, I think deleting object files each build doesn't make too much sense, as it will force you to rebuild them even if their source files have not been modified.
