### ISSUE TITLE
Patch to SGDK needed for make to succeed

### ISSUE THREAD

**Issue by lifning** [kubilus1/gendev#14]
[gendev-sgdk-src-vram-c.txt](https://github.com/kubilus1/gendev/files/243896/gendev-sgdk-src-vram-c.txt)

**Comment by kubilus1** [comment]
Thanks for the heads up!  I've created a packaged this and created a pull request for the SGDK project: https://github.com/Stephane-D/SGDK/pull/66

**Comment by kubilus1** [comment]
I went ahead and just linked to my fork of SGDK until this is resolved in that project.
