### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by yazoo178** [kubilus1/gendev#16]
Sorry I might be missing something, but i've followed the read me/wiki setup guide and i'm getting a build error after typing 'make':

newlib-1.19.0/libgloss/hp74x/checksum.c
newlib-1.19.0/libgloss/hp74x/hppa-defs.h
newlib-1.19.0/libgloss/unlink.c
newlib-1.19.0/libgloss/doc/
newlib-1.19.0/libgloss/doc/configure.in
newlib-1.19.0/libgloss/doc/Makefile.in
newlib-1.19.0/libgloss/doc/configure
newlib-1.19.0/libgloss/doc/porting.texi
newlib-1.19.0/libgloss/mn10300/
newlib-1.19.0/libgloss/mn10300/execv.c
newlib-1.19.0/libgloss/mn10300/trap.h
newlib-1.19.0/libgloss/mn10300/asb2303.ld
newlib-1.19.0/libgloss/mn10300/aclocal.m4
newlib-1.19.0/libgloss/mn10300/open.c
newlib-1.19.0/libgloss/mn10300/trap.S
newlib-1.19.0/libgloss/mn10300/crt0_cygmon.S
newlib-1.19.0/libgloss/mn10300/gettime.c
newlib-1.19.0/libgloss/mn10300/crt0.S
newlib-1.19.0/libgloss/mn10300/getpid.c
newlib-1.19.0/libgloss/mn10300/configure.in
newlib-1.19.0/libgloss/mn10300/creat.c
newlib-1.19.0/libgloss/mn10300/Makefile.in
newlib-1.19.0/libgloss/mn10300/eval.ld
newlib-1.19.0/libgloss/mn10300/lseek.c
newlib-1.19.0/libgloss/mn10300/access.c
newlib-1.19.0/libgloss/mn10300/crt1.c
newlib-1.19.0/libgloss/mn10300/crt0-eval.S
newlib-1.19.0/libgloss/mn10300/_exit.c
newlib-1.19.0/libgloss/mn10300/sim.ld
newlib-1.19.0/libgloss/mn10300/chmod.c
newlib-1.19.0/libgloss/mn10300/pipe.c
newlib-1.19.0/libgloss/mn10300/write.c
newlib-1.19.0/libgloss/mn10300/utime.c
newlib-1.19.0/libgloss/mn10300/test.c
newlib-1.19.0/libgloss/mn10300/close.c
newlib-1.19.0/libgloss/mn10300/wait.c
newlib-1.19.0/libgloss/mn10300/sbrk.c
newlib-1.19.0/libgloss/mn10300/read.c
newlib-1.19.0/libgloss/mn10300/chown.c
newlib-1.19.0/libgloss/mn10300/asb2305.ld
newlib-1.19.0/libgloss/mn10300/configure
newlib-1.19.0/libgloss/mn10300/stat.c
newlib-1.19.0/libgloss/mn10300/isatty.c
newlib-1.19.0/libgloss/mn10300/cygmon.c
newlib-1.19.0/libgloss/mn10300/kill.c
newlib-1.19.0/libgloss/mn10300/fstat.c
newlib-1.19.0/libgloss/mn10300/crt0_redboot.S
newlib-1.19.0/libgloss/mn10300/time.c
newlib-1.19.0/libgloss/mn10300/execve.c
newlib-1.19.0/libgloss/mn10300/unlink.c
newlib-1.19.0/libgloss/mn10300/fork.c
newlib-1.19.0/libgloss/mn10300/times.c
newlib-1.19.0/libgloss/mn10200/
newlib-1.19.0/libgloss/mn10200/execv.c
newlib-1.19.0/libgloss/mn10200/trap.h
newlib-1.19.0/libgloss/mn10200/aclocal.m4
newlib-1.19.0/libgloss/mn10200/open.c
newlib-1.19.0/libgloss/mn10200/trap.S
newlib-1.19.0/libgloss/mn10200/gettime.c
newlib-1.19.0/libgloss/mn10200/crt0.S
newlib-1.19.0/libgloss/mn10200/getpid.c
newlib-1.19.0/libgloss/mn10200/configure.in
newlib-1.19.0/libgloss/mn10200/creat.c
newlib-1.19.0/libgloss/mn10200/Makefile.in
newlib-1.19.0/libgloss/mn10200/eval.ld
newlib-1.19.0/libgloss/mn10200/lseek.c
newlib-1.19.0/libgloss/mn10200/access.c
newlib-1.19.0/libgloss/mn10200/crt1.c
newlib-1.19.0/libgloss/mn10200/_exit.c
newlib-1.19.0/libgloss/mn10200/sim.ld
newlib-1.19.0/libgloss/mn10200/chmod.c
newlib-1.19.0/libgloss/mn10200/pipe.c
newlib-1.19.0/libgloss/mn10200/write.c
newlib-1.19.0/libgloss/mn10200/utime.c
newlib-1.19.0/libgloss/mn10200/test.c
newlib-1.19.0/libgloss/mn10200/close.c
newlib-1.19.0/libgloss/mn10200/wait.c
newlib-1.19.0/libgloss/mn10200/sbrk.c
newlib-1.19.0/libgloss/mn10200/read.c
newlib-1.19.0/libgloss/mn10200/chown.c
newlib-1.19.0/libgloss/mn10200/configure
newlib-1.19.0/libgloss/mn10200/stat.c
newlib-1.19.0/libgloss/mn10200/isatty.c
newlib-1.19.0/libgloss/mn10200/kill.c
newlib-1.19.0/libgloss/mn10200/fstat.c
newlib-1.19.0/libgloss/mn10200/time.c
newlib-1.19.0/libgloss/mn10200/execve.c
newlib-1.19.0/libgloss/mn10200/unlink.c
newlib-1.19.0/libgloss/mn10200/fork.c
newlib-1.19.0/libgloss/mn10200/times.c
newlib-1.19.0/libgloss/frv/
newlib-1.19.0/libgloss/frv/aclocal.m4
newlib-1.19.0/libgloss/frv/crt0.S
newlib-1.19.0/libgloss/frv/sim-exit.S
newlib-1.19.0/libgloss/frv/getpid.c
newlib-1.19.0/libgloss/frv/configure.in
newlib-1.19.0/libgloss/frv/Makefile.in
newlib-1.19.0/libgloss/frv/sim-close.S
newlib-1.19.0/libgloss/frv/sim-unlink.S
newlib-1.19.0/libgloss/frv/sim-inbyte.c
newlib-1.19.0/libgloss/frv/sbrk.c
newlib-1.19.0/libgloss/frv/sim-lseek.S
newlib-1.19.0/libgloss/frv/sim-open.S
newlib-1.19.0/libgloss/frv/configure
newlib-1.19.0/libgloss/frv/stat.c
newlib-1.19.0/libgloss/frv/isatty.c
newlib-1.19.0/libgloss/frv/putnum.c
newlib-1.19.0/libgloss/frv/sim-time.c
newlib-1.19.0/libgloss/frv/print.c
newlib-1.19.0/libgloss/frv/sim-write.S
newlib-1.19.0/libgloss/frv/kill.c
newlib-1.19.0/libgloss/frv/fstat.c
newlib-1.19.0/libgloss/frv/sim-read.S
newlib-1.19.0/libgloss/microblaze/
newlib-1.19.0/libgloss/microblaze/xil_sbrk.c
newlib-1.19.0/libgloss/microblaze/sim-pgcrtinit.S
newlib-1.19.0/libgloss/microblaze/_program_init.S
newlib-1.19.0/libgloss/microblaze/crt0.S
newlib-1.19.0/libgloss/microblaze/configure.in
newlib-1.19.0/libgloss/microblaze/crt1.S
newlib-1.19.0/libgloss/microblaze/xilinx.ld
newlib-1.19.0/libgloss/microblaze/Makefile.in
newlib-1.19.0/libgloss/microblaze/xil_malloc.c
newlib-1.19.0/libgloss/microblaze/_exception_handler.S
newlib-1.19.0/libgloss/microblaze/crt4.S
newlib-1.19.0/libgloss/microblaze/pgcrtinit.S
newlib-1.19.0/libgloss/microblaze/sim-crtinit.S
newlib-1.19.0/libgloss/microblaze/sbrk.c
newlib-1.19.0/libgloss/microblaze/_program_clean.S
newlib-1.19.0/libgloss/microblaze/configure
newlib-1.19.0/libgloss/microblaze/crt2.S
newlib-1.19.0/libgloss/microblaze/timer.c
newlib-1.19.0/libgloss/microblaze/_hw_exception_handler.S
newlib-1.19.0/libgloss/microblaze/_interrupt_handler.S
newlib-1.19.0/libgloss/microblaze/crt3.S
newlib-1.19.0/libgloss/microblaze/crtinit.S
newlib-1.19.0/libgloss/sh/
newlib-1.19.0/libgloss/sh/sh3lcevb.ld
newlib-1.19.0/libgloss/sh/sh2lcevb.ld
newlib-1.19.0/libgloss/sh/sh1lcevb.ld
newlib-1.19.0/libgloss/sh/sh3bb.ld
newlib-1.19.0/COPYING.LIB
newlib-1.19.0/ltsugar.m4
newlib-1.19.0/Makefile.def
newlib-1.19.0/ltmain.sh
newlib-1.19.0/depcomp
newlib-1.19.0/Makefile.in
newlib-1.19.0/ChangeLog
newlib-1.19.0/Makefile.tpl
newlib-1.19.0/.cvsignore
newlib-1.19.0/ylwrap
newlib-1.19.0/makefile.vms
newlib-1.19.0/config.rpath
newlib-1.19.0/configure.ac
newlib-1.19.0/missing
newlib-1.19.0/COPYING.LIBGLOSS
newlib-1.19.0/texinfo/
newlib-1.19.0/texinfo/texinfo.tex
newlib-1.19.0/COPYING3.LIB
newlib-1.19.0/ltgcc.m4
newlib-1.19.0/config.sub
newlib-1.19.0/COPYING
newlib-1.19.0/configure
newlib-1.19.0/config.guess
newlib-1.19.0/libtool.m4
newlib-1.19.0/config/
newlib-1.19.0/config/lib-ld.m4
newlib-1.19.0/config/glibc21.m4
newlib-1.19.0/config/lib-link.m4
newlib-1.19.0/config/bootstrap-lto.mk
newlib-1.19.0/config/lthostflags.m4
newlib-1.19.0/config/mh-sco
newlib-1.19.0/config/inttypes-pri.m4
newlib-1.19.0/config/no-executables.m4
newlib-1.19.0/config/unwind_ipinfo.m4
newlib-1.19.0/config/largefile.m4
newlib-1.19.0/config/codeset.m4
newlib-1.19.0/config/mt-sde
newlib-1.19.0/config/warnings.m4
newlib-1.19.0/config/tls.m4
newlib-1.19.0/config/bootstrap-debug-lib.mk
newlib-1.19.0/config/multi.m4
newlib-1.19.0/config/stdint.m4
newlib-1.19.0/config/elf.m4
newlib-1.19.0/config/mt-spu
newlib-1.19.0/config/bootstrap-O1.mk
newlib-1.19.0/config/mt-alphaieee
newlib-1.19.0/config/mh-pa-hpux10
newlib-1.19.0/config/ChangeLog
newlib-1.19.0/config/mh-dgux386
newlib-1.19.0/config/bootstrap-O3.mk
newlib-1.19.0/config/cloog.m4
newlib-1.19.0/config/extensions.m4
newlib-1.19.0/config/mt-wince
newlib-1.19.0/config/mh-solaris
newlib-1.19.0/config/mh-x86omitfp
newlib-1.19.0/config/plugins.m4
newlib-1.19.0/config/inttypes.m4
newlib-1.19.0/config/mh-lynxrs6k
newlib-1.19.0/config/bootstrap-debug-big.mk
newlib-1.19.0/config/depstand.m4
newlib-1.19.0/config/proginstall.m4
newlib-1.19.0/config/mh-necv4
newlib-1.19.0/config/mh-cxux
newlib-1.19.0/config/mt-mips16-compat
newlib-1.19.0/config/mh-interix
newlib-1.19.0/config/nls.m4
newlib-1.19.0/config/gxx-include-dir.m4
newlib-1.19.0/config/mh-pa
newlib-1.19.0/config/mt-netware
newlib-1.19.0/config/mh-mingw
newlib-1.19.0/config/acx.m4
newlib-1.19.0/config/acinclude.m4
newlib-1.19.0/config/mh-sysv4
newlib-1.19.0/config/progtest.m4
newlib-1.19.0/config/mt-v810
newlib-1.19.0/config/mh-ncr3000
newlib-1.19.0/config/mt-gnu
newlib-1.19.0/config/dfp.m4
newlib-1.19.0/config/bootstrap-debug-ckovw.mk
newlib-1.19.0/config/tcl.m4
newlib-1.19.0/config/intdiv0.m4
newlib-1.19.0/config/mh-decstation
newlib-1.19.0/config/gettext.m4
newlib-1.19.0/config/inttypes_h.m4
newlib-1.19.0/config/lib-prefix.m4
newlib-1.19.0/config/futex.m4
newlib-1.19.0/config/gc++filt.m4
newlib-1.19.0/config/lcmessage.m4
newlib-1.19.0/config/mt-ospace
newlib-1.19.0/config/mh-ppc-aix
newlib-1.19.0/config/bootstrap-time.mk
newlib-1.19.0/config/ulonglong.m4
newlib-1.19.0/config/mh-sysv5
newlib-1.19.0/config/po.m4
newlib-1.19.0/config/iconv.m4
newlib-1.19.0/config/mh-cygwin
newlib-1.19.0/config/mt-d30v
newlib-1.19.0/config/lead-dot.m4
newlib-1.19.0/config/enable.m4
newlib-1.19.0/config/gettext-sister.m4
newlib-1.19.0/config/zlib.m4
newlib-1.19.0/config/mt-mips-elfoabi
newlib-1.19.0/config/mh-djgpp
newlib-1.19.0/config/override.m4
newlib-1.19.0/config/bootstrap-debug-lean.mk
newlib-1.19.0/config/uintmax_t.m4
newlib-1.19.0/config/ld-symbolic.m4
newlib-1.19.0/config/mh-darwin
newlib-1.19.0/config/stdint_h.m4
newlib-1.19.0/config/mt-mips-gnu
newlib-1.19.0/config/bootstrap-debug.mk
newlib-1.19.0/config/mt-mep
newlib-1.19.0/COPYING.NEWLIB
newlib-1.19.0/lt~obsolete.m4
newlib-1.19.0/README
newlib-1.19.0/mkinstalldirs
newlib-1.19.0/ltoptions.m4
newlib-1.19.0/COPYING3
newlib-1.19.0/move-if-change
newlib-1.19.0/install-sh
newlib-1.19.0/mkdep
newlib-1.19.0/MAINTAINERS
newlib-1.19.0/ltversion.m4
newlib-1.19.0/config-ml.in
newlib-1.19.0/README-maintainer-mode
newlib-1.19.0/setup.com
echo "Build"
Build
cd work && \
        MAKE=make make -f ../gen_gcc/makefile-gen build-m68k
make[1]: Entering directory `/home/a/gendev/work'
+++ Building binutils-2.24 to build-binutils-m68k-elf-2.24...
mkdir -p build-binutils-m68k-elf-2.24

> /home/a/gendev/work/logs/build-binutils-m68k-elf-2.24.log
> cd build-binutils-m68k-elf-2.24; ../binutils-2.24/configure --target=m68k-elf --prefix=/opt/toolchains/gen/m68k-elf --enable-install-libbfd --disable-werror >> /home/a/gendev/work/logs/build-binutils-m68k-elf-2.24.log 2>&1
> make -C build-binutils-m68k-elf-2.24 all install DESTDIR= >> /home/a/gendev/work/logs/build-binutils-m68k-elf-2.24.log 2>&1
> +++ Building gcc-4.8.2 to build-gcc-m68k-elf-4.8.2 (pass 1)...
> mkdir -p build-gcc-m68k-elf-4.8.2
> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass1.log
> cd build-gcc-m68k-elf-4.8.2;  ../gcc-4.8.2/configure --target=m68k-elf --prefix=/opt/toolchains/gen/m68k-elf --without-headers --with-newlib --enable-languages=c --disable-libssp --disable-tls --with-cpu=m68000 --disable-werror >> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass1.log 2>&1
> make -C build-gcc-m68k-elf-4.8.2 all install DESTDIR= >> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass1.log 2>&1
> +++ Building newlib-1.19.0 to build-newlib-m68k-elf-1.19.0...
> mkdir -p build-newlib-m68k-elf-1.19.0
> /home/a/gendev/work/logs/build-newlib-m68k-elf-1.19.0.log
> cd build-newlib-m68k-elf-1.19.0; ../newlib-1.19.0/configure --target=m68k-elf --prefix=/opt/toolchains/gen/m68k-elf --with-cpu=m68000 --disable-werror >> /home/a/gendev/work/logs/build-newlib-m68k-elf-1.19.0.log 2>&1
> make -C build-newlib-m68k-elf-1.19.0 all install DESTDIR= >> /home/a/gendev/work/logs/build-newlib-m68k-elf-1.19.0.log 2>&1
> +++ Building gcc-4.8.2 to build-gcc-m68k-elf-4.8.2 (pass 2)...
> mkdir -p build-gcc-m68k-elf-4.8.2
> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass2.log
> cd build-gcc-m68k-elf-4.8.2;  ../gcc-4.8.2/configure --target=m68k-elf --prefix=/opt/toolchains/gen/m68k-elf --with-newlib --disable-libssp --disable-tls \
>         --enable-threads=single --enable-languages=c --with-cpu=m68000 --disable-werror >> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass2.log 2>&1
> make -C build-gcc-m68k-elf-4.8.2 all install DESTDIR= >> /home/a/gendev/work/logs/build-gcc-m68k-elf-4.8.2-pass2.log 2>&1
> make[1]: Leaving directory `/home/a/gendev/work'
> cp extras/scripts/* /opt/toolchains/gen/bin/.
> cp: omitting directory ‘extras/scripts/timez80’
> make: [tools] Error 1 (ignored)
> echo "Done with tools."
> Done with tools.
> cd sgdk && make install     
> make[1]: Entering directory`/home/a/gendev/sgdk'
> cd sgdk-read-only/tools/bintos/src && \
>     gcc -o bintos bintos.c  && cp bintos /opt/toolchains/gen//bin/.
> cd sgdk-read-only/tools/pcmtoraw/src && \
>     gcc -o pcmtoraw pcmtoraw.c  && cp pcmtoraw /opt/toolchains/gen//bin/.
> cd sgdk-read-only/tools/sizebnd/src && \
>     gcc -o sizebnd sizebnd.c  && cp sizebnd /opt/toolchains/gen//bin/.
> cd sgdk-read-only/tools/wavtoraw/src && \
>     gcc -o wavtoraw wavtoraw.c -lm && cp wavtoraw /opt/toolchains/gen//bin/.
> wavtoraw.c: In function ‘main’:
> wavtoraw.c:59:5: warning: format ‘%c’ expects argument of type ‘char _’, but argument 3 has type ‘uint32_t *’ [-Wformat=]
>      saferead( infile, "%4c", &nChunkSize );
>      ^
> wavtoraw.c:62:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘uint32_t *’ [-Wformat=]
>      saferead( infile, "%4c", &nChunkSize );
>      ^
> wavtoraw.c:63:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘short int *’ [-Wformat=]
>      saferead( infile, "%2c", &wFormatTag );
>      ^
> wavtoraw.c:64:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘short int *’ [-Wformat=]
>      saferead( infile, "%2c", &nChannels );
>      ^
> wavtoraw.c:65:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘uint32_t *’ [-Wformat=]
>      saferead( infile, "%4c", &nSamplesPerSecond );
>      ^
> wavtoraw.c:66:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘uint32_t *’ [-Wformat=]
>      saferead( infile, "%4c", &nBytesPerSecond );
>      ^
> wavtoraw.c:67:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘short int *’ [-Wformat=]
>      saferead( infile, "%2c", &nBlockAlign );
>      ^
> wavtoraw.c:68:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘short int *’ [-Wformat=]
>      saferead( infile, "%2c", &nBitsPerSample );
>      ^
> wavtoraw.c:72:9: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘int *’ [-Wformat=]
>          saferead( infile, "%1c", &j);
>          ^
> wavtoraw.c:75:5: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘uint32_t *’ [-Wformat=]
>      saferead( infile, "%4c", &nChunkSize );
>      ^
> wavtoraw.c: In function ‘nextSample’:
> wavtoraw.c:174:17: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘short int *’ [-Wformat=]
>                  fscanf( file, "%2c", &w );
>                  ^
> wavtoraw.c:179:17: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘long int *’ [-Wformat=]
>                  fscanf( file, "%3c", &l );
>                  ^
> wavtoraw.c:184:17: warning: format ‘%c’ expects argument of type ‘char *’, but argument 3 has type ‘long int *’ [-Wformat=]
>                  fscanf( file, "%4c", &l );
>                  ^
> cd sgdk-read-only/tools/xgmtool && \
>         make -f ../../../files/Makefile.xgmtool && cp out/xgmtool /opt/toolchains/gen//bin/.
> make[2]: Entering directory `/home/a/gendev/sgdk/sgdk-read-only/tools/xgmtool'
> ../../../files/Makefile.xgmtool:118: warning: overriding commands for target`out/src/psg.o'
> ../../../files/Makefile.xgmtool:63: warning: ignoring old commands for target `out/src/psg.o'
> ../../../files/Makefile.xgmtool:121: warning: overriding commands for target`out/src/ym2612.o'
> ../../../files/Makefile.xgmtool:66: warning: ignoring old commands for target `out/src/ym2612.o'
> ../../../files/Makefile.xgmtool:124: warning: overriding commands for target`out/src/xgmtool.o'
> ../../../files/Makefile.xgmtool:69: warning: ignoring old commands for target `out/src/xgmtool.o'
> ../../../files/Makefile.xgmtool:127: warning: overriding commands for target`out/src/xgmsmp.o'
> ../../../files/Makefile.xgmtool:72: warning: ignoring old commands for target `out/src/xgmsmp.o'
> ../../../files/Makefile.xgmtool:130: warning: overriding commands for target`out/src/xgmcom.o'
> ../../../files/Makefile.xgmtool:75: warning: ignoring old commands for target `out/src/xgmcom.o'
> ../../../files/Makefile.xgmtool:133: warning: overriding commands for target`out/src/xgm.o'
> ../../../files/Makefile.xgmtool:78: warning: ignoring old commands for target `out/src/xgm.o'
> ../../../files/Makefile.xgmtool:136: warning: overriding commands for target`out/src/xgccom.o'
> ../../../files/Makefile.xgmtool:81: warning: ignoring old commands for target `out/src/xgccom.o'
> ../../../files/Makefile.xgmtool:139: warning: overriding commands for target`out/src/xgc.o'
> ../../../files/Makefile.xgmtool:84: warning: ignoring old commands for target `out/src/xgc.o'
> ../../../files/Makefile.xgmtool:142: warning: overriding commands for target`out/src/vgmcom.o'
> ../../../files/Makefile.xgmtool:87: warning: ignoring old commands for target `out/src/vgmcom.o'
> ../../../files/Makefile.xgmtool:145: warning: overriding commands for target`out/src/vgm.o'
> ../../../files/Makefile.xgmtool:90: warning: ignoring old commands for target `out/src/vgm.o'
> ../../../files/Makefile.xgmtool:148: warning: overriding commands for target`out/src/util.o'
> ../../../files/Makefile.xgmtool:93: warning: ignoring old commands for target `out/src/util.o'
> ../../../files/Makefile.xgmtool:151: warning: overriding commands for target`out/src/samplebank.o'
> ../../../files/Makefile.xgmtool:96: warning: ignoring old commands for target `out/src/samplebank.o'
> ../../../files/Makefile.xgmtool:154: warning: overriding commands for target`out/src/gd3.o'
> ../../../files/Makefile.xgmtool:99: warning: ignoring old commands for target `out/src/gd3.o'
> test -d out || mkdir -p out
> test -d out/src || mkdir -p out/src
> g++  -o out/xgmtool out/src/psg.o out/src/ym2612.o out/src/xgmtool.o out/src/xgmsmp.o out/src/xgmcom.o out/src/xgm.o out/src/xgccom.o out/src/xgc.o out/src/vgmcom.o out/src/vgm.o out/src/util.o out/src/samplebank.o out/src/gd3.o   -s 
> test -d out || mkdir -p out
> test -d out/src || mkdir -p out/src
> g++  -o out/xgmtool out/src/psg.o out/src/ym2612.o out/src/xgmtool.o out/src/xgmsmp.o out/src/xgmcom.o out/src/xgm.o out/src/xgccom.o out/src/xgc.o out/src/vgmcom.o out/src/vgm.o out/src/util.o out/src/samplebank.o out/src/gd3.o   
> make[2]: Leaving directory`/home/a/gendev/sgdk/sgdk-read-only/tools/xgmtool'
> cd sgdk-read-only/tools/rescomp && \
>         patch -u -p0 < ../../../files/rescomp.diff && \
>         make -f ../../../files/Makefile.rescomp && cp out/rescomp /opt/toolchains/gen//bin/.
> patching file inc/tools.h
> patching file src/tools.c
> make[2]: Entering directory `/home/a/gendev/sgdk/sgdk-read-only/tools/rescomp'
> ../../../files/Makefile.rescomp:136: warning: overriding commands for target`out/src/snd_tools.o'
> ../../../files/Makefile.rescomp:63: warning: ignoring old commands for target `out/src/snd_tools.o'
> ../../../files/Makefile.rescomp:139: warning: overriding commands for target`out/src/bin.o'
> ../../../files/Makefile.rescomp:66: warning: ignoring old commands for target `out/src/bin.o'
> ../../../files/Makefile.rescomp:142: warning: overriding commands for target`out/src/bitmap.o'
> ../../../files/Makefile.rescomp:69: warning: ignoring old commands for target `out/src/bitmap.o'
> ../../../files/Makefile.rescomp:145: warning: overriding commands for target`out/src/image.o'
> ../../../files/Makefile.rescomp:72: warning: ignoring old commands for target `out/src/image.o'
> ../../../files/Makefile.rescomp:148: warning: overriding commands for target`out/src/img_tools.o'
> ../../../files/Makefile.rescomp:75: warning: ignoring old commands for target `out/src/img_tools.o'
> ../../../files/Makefile.rescomp:151: warning: overriding commands for target`out/src/libpng.o'
> ../../../files/Makefile.rescomp:78: warning: ignoring old commands for target `out/src/libpng.o'
> ../../../files/Makefile.rescomp:154: warning: overriding commands for target`out/src/map.o'
> ../../../files/Makefile.rescomp:81: warning: ignoring old commands for target `out/src/map.o'
> ../../../files/Makefile.rescomp:157: warning: overriding commands for target`out/src/palette.o'
> ../../../files/Makefile.rescomp:84: warning: ignoring old commands for target `out/src/palette.o'
> ../../../files/Makefile.rescomp:160: warning: overriding commands for target`out/src/pcm.o'
> ../../../files/Makefile.rescomp:87: warning: ignoring old commands for target `out/src/pcm.o'
> ../../../files/Makefile.rescomp:163: warning: overriding commands for target`out/src/rescomp.o'
> ../../../files/Makefile.rescomp:90: warning: ignoring old commands for target `out/src/rescomp.o'
> ../../../files/Makefile.rescomp:166: warning: overriding commands for target`out/src/spr_tools.o'
> ../../../files/Makefile.rescomp:93: warning: ignoring old commands for target `out/src/spr_tools.o'
> ../../../files/Makefile.rescomp:169: warning: overriding commands for target`out/src/sprite.o'
> ../../../files/Makefile.rescomp:96: warning: ignoring old commands for target `out/src/sprite.o'
> ../../../files/Makefile.rescomp:172: warning: overriding commands for target`out/src/tfmmusic.o'
> ../../../files/Makefile.rescomp:99: warning: ignoring old commands for target `out/src/tfmmusic.o'
> ../../../files/Makefile.rescomp:175: warning: overriding commands for target`out/src/tile_tools.o'
> ../../../files/Makefile.rescomp:102: warning: ignoring old commands for target `out/src/tile_tools.o'
> ../../../files/Makefile.rescomp:178: warning: overriding commands for target`out/src/tileset.o'
> ../../../files/Makefile.rescomp:105: warning: ignoring old commands for target `out/src/tileset.o'
> ../../../files/Makefile.rescomp:181: warning: overriding commands for target`out/src/tools.o'
> ../../../files/Makefile.rescomp:108: warning: ignoring old commands for target `out/src/tools.o'
> ../../../files/Makefile.rescomp:184: warning: overriding commands for target`out/src/vgmmusic.o'
> ../../../files/Makefile.rescomp:111: warning: ignoring old commands for target `out/src/vgmmusic.o'
> ../../../files/Makefile.rescomp:187: warning: overriding commands for target`out/src/wav.o'
> ../../../files/Makefile.rescomp:114: warning: ignoring old commands for target `out/src/wav.o'
> ../../../files/Makefile.rescomp:190: warning: overriding commands for target`out/src/xgmmusic.o'
> ../../../files/Makefile.rescomp:117: warning: ignoring old commands for target `out/src/xgmmusic.o'
> test -d out || mkdir -p out
> test -d out/src || mkdir -p out/src
> gcc -Wall -O2  -c src/tools.c -o out/src/tools.o
> src/tools.c: In function ‘packEx’:
> src/tools.c:543:30: warning: variable ‘size4’ set but not used [-Wunused-but-set-variable]
>      int size1, size2, size3, size4;
>                               ^
> src/tools.c: In function ‘readFile’:
> src/tools.c:277:10: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
>      fread(data, 1, *size, f);
>           ^
> src/tools.c: In function ‘appack’:
> src/tools.c:805:11: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
>      system(cmd);
>            ^
> src/tools.c: In function ‘maccer’:
> src/tools.c:690:11: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
>      system(cmd);
>            ^
> src/tools.c: In function ‘tfmcom’:
> src/tools.c:720:11: warning: ignoring return value of ‘system’, declared with attribute warn_unused_result [-Wunused-result]
>      system(cmd);
>            ^
> g++  -o out/rescomp out/src/snd_tools.o out/src/bin.o out/src/bitmap.o out/src/image.o out/src/img_tools.o out/src/libpng.o out/src/map.o out/src/palette.o out/src/pcm.o out/src/rescomp.o out/src/spr_tools.o out/src/sprite.o out/src/tfmmusic.o out/src/tile_tools.o out/src/tileset.o out/src/tools.o out/src/vgmmusic.o out/src/wav.o out/src/xgmmusic.o   
> test -d out || mkdir -p out
> test -d out/src || mkdir -p out/src
> g++  -o out/rescomp out/src/snd_tools.o out/src/bin.o out/src/bitmap.o out/src/image.o out/src/img_tools.o out/src/libpng.o out/src/map.o out/src/palette.o out/src/pcm.o out/src/rescomp.o out/src/spr_tools.o out/src/sprite.o out/src/tfmmusic.o out/src/tile_tools.o out/src/tileset.o out/src/tools.o out/src/vgmmusic.o out/src/wav.o out/src/xgmmusic.o   -s 
> make[2]: Leaving directory`/home/a/gendev/sgdk/sgdk-read-only/tools/rescomp'
> cd sgdk-read-only && ln -sf ../files/Makefile.sgdk_lib .
> cd sgdk-read-only && make -f Makefile.sgdk_lib 
> make[2]: Entering directory `/home/a/gendev/sgdk/sgdk-read-only'
> /opt/toolchains/gen//m68k-elf/bin/m68k-elf-gcc  -Dnologo_  -m68000 -Wall -O1 -c -fomit-frame-pointer -Iinc -Ires  -c src/vram.c -o src/vram.o 
> In file included from src/vram.c:7:0:
> inc/memory.h:199:6: warning: conflicting types for built-in function ‘memset’ [enabled by default]
>  void memset(void *to, u8 value, u16 len);
>       ^
> inc/memory.h:242:6: warning: conflicting types for built-in function ‘memcpy’ [enabled by default]
>  void memcpy(void *to, const void *from, u16 len);
>       ^
> src/vram.c:161:18: error: unknown type name ‘VRAMRegion’
>  static u16_ pack(VRAMRegion _region, u16 nsize);
>                   ^
> src/vram.c:164:24: error: unknown type name ‘VRAMRegion’
>  void VRAM_createRegion(VRAMRegion *region, u16 startIndex, u16 size)
>                         ^
> src/vram.c:177:25: error: unknown type name ‘VRAMRegion’
>  void VRAM_releaseRegion(VRAMRegion *region)
>                          ^
> src/vram.c:184:23: error: unknown type name ‘VRAMRegion’
>  void VRAM_clearRegion(VRAMRegion *region)
>                        ^
> src/vram.c:197:16: error: unknown type name ‘VRAMRegion’
>  s16 VRAM_alloc(VRAMRegion *region, u16 size)
>                 ^
> src/vram.c:254:16: error: unknown type name ‘VRAMRegion’
>  void VRAM_free(VRAMRegion *region, u16 index)
>                 ^
> src/vram.c:263:18: error: unknown type name ‘VRAMRegion’
>  u16 VRAM_getFree(VRAMRegion *region)
>                   ^
> src/vram.c:292:18: error: unknown type name ‘VRAMRegion’
>  static u16_ pack(VRAMRegion _region, u16 nsize)
>                   ^
> make[2]: *_\* [src/vram.o] Error 1
> make[2]: Leaving directory `/home/a/gendev/sgdk/sgdk-read-only'
> make[1]: *** [sgdk-read-only/libmd.a] Error 2
> make[1]: Leaving directory`/home/a/gendev/sgdk'
> make: **\* [/opt/toolchains/gen/m68k-elf/lib/libmd.a] Error 2
> a@ubuntu:~/gendev$

**Comment by kubilus1** [comment]
Looks like a build issue from the linked sgdk project.  I've linked to my fork of SGDK for now to resolve this.  Pull the latest and try again!
