### ISSUE TITLE
SGDK 1.2 changes needed to build successfully

### ISSUE THREAD

**Issue by andwn** [kubilus1/gendev#17]
I ported my project to the new SGDK version and had to make a couple changes to gendev:
1. Update sega.s in the skeleton (project) to the new one
2. Copy sgdk-read-only/bin/lz2w.jar to $(GENDEV)/bin (BEFORE compiling libmd, it's a dependency)

There's 2 less mysteries for you to solve hopefully.

**Comment by kubilus1** [comment]
Thanks for the tips, this should all be incorporated (actually a bit ago but I've been lazy with issues)
