### ISSUE TITLE
Software License?

### ISSUE THREAD

**Issue by jgyllinsky** [kubilus1/gendev#18]
What is the software license? Is this BSD3 (https://opensource.org/licenses/BSD-3-Clause), like the google code repo for gendev at https://code.google.com/archive/p/gendev/?

**Comment by felipesanches** [comment]
yeah... I hope so. That's at least what one would guess based on the project's previous life at another code hosting platform :-P

**Comment by felipesanches** [comment]
@jgyllinsky can you send a pull request adding a **LICENSE** file? Maybe that will make it trivial for @kubilus1 to acknowledge the proper license by merging the pull request.

**Comment by kubilus1** [comment]
Yes, I think BSD-3 still makes sense.  Though this is mostly tooling related so not much here should really effect an end product, but better to cover the bases.

**Comment by felipesanches** [comment]
https://github.com/kubilus1/gendev/commit/aee7171255ac0c60982d426e48da878b7a2e80e0

Thanks! :-D
