### ISSUE TITLE
What needs to happen to merge with SGDK1.22a?

### ISSUE THREAD

**Issue by jgyllinsky** [kubilus1/gendev#19]
What needs to happen to merge with SGDK1.22a , and how can I help?

**Comment by bu95bunny** [comment]
I think, we should ask "what should we change in original SGDK to successfully build it on linux", so we could help with the project and keep it up to date.

**Comment by ghost** [comment]
SGDK is 1.30 now, but still no library updates here :( is gendev dead?

**Comment by kubilus1** [comment]
Yeah, there hasn't been a ton of time lately, but I hope to pick some of this back up.  I'm looking at trying to compile SGDK 1.30, hopefully this won't be too difficult.

**Comment by kubilus1** [comment]
This project should be SGDK 1.3 compatible now.
