### ISSUE TITLE
Can't build ROMs with gendev.

### ISSUE THREAD

**Issue by ghost** [kubilus1/gendev#26]
Gendev itself built fine, with no errors. But when I'm trying to build the ROM...

> /opt/toolchains/gen//m68k-elf/bin/m68k-elf-ld: cannot find /opt/toolchains/gen//m68k-elf/lib/gcc/m68k-elf/4.8.2/libgcc.a: No such file or directory
> Makefile:135: recipe for target 'out.elf' failed
> make: *** [out.elf] Error 1

This error appeared not so long ago, changing my linux distribution didn't help.

**Comment by andwn** [comment]
Probably need to update your project's Makefile to look in /6.3.0/ directory instead of /4.8.2/

**Comment by ghost** [comment]
Yes, this helped! Thanks :)
