### ISSUE TITLE
SGDK looks old

### ISSUE THREAD

**Issue by kivutar** [kubilus1/gendev#28]
I tried this nice project (the docker container version).

It happens that there are no definition of SPR_addSprite. I took a look on the web, and found that it should be in sprite_eng.h.

In your sprite_eng.h, I find an old sprite api, with SPR_initSprite.

**Comment by kubilus1** [comment]
Currently this project is using the 1.2 version of SGDK.  Hopefully SGDK 1.3 can be ported over before too long.

**Comment by kivutar** [comment]
Ok I get it. I'll stick with 1.2 for now then.
