### ISSUE TITLE
<stdint.h> must be included before <genesis.h>

### ISSUE THREAD

**Issue by minerscale** [kubilus1/gendev#33]
Hello. While I was trying to get the Echo sound engine working with my game, I realised that it won't let me include <stdint.h>. So I created a new project with the absoloute bare minimum and the (bug?) is repeatable.

Here's my test rig:

[test.zip](https://github.com/kubilus1/gendev/files/1185366/test.zip)

And here's the error(s):

`In file included from /opt/gendev/sgdk/inc/genesis.h:7:0,
                 from main.c:1:
/opt/gendev/sgdk/inc/types.h:142:21: error: conflicting types for 's8'
 #define int8_t      s8
                     ^
/opt/gendev/sgdk/inc/types.h:79:14: note: previous declaration of 's8' was here
 typedef char s8;
              ^~
`

Any help getting this up and running would be greatly appreciated, and if it's an SGDK bug lemme know so I can put this bug report into SGDK. Meanwhile I'll try to find a solution

**Comment by minerscale** [comment]
Ok, I found a workaround? I just changed the order I included the files. If I include <stdint.h> before <genesis.h> it compiles. But if I do it the other way around, it doesn't.

Does this still pass as a bug? Are there other examples of this happening?

**Comment by andwn** [comment]
SGDK defines the types (like uint16_t etc) if it detects that stdint.h is not included. Of course, if stdint.h is included after, it won't detect it, so there you get the "conflicting types" due to SGDK defining it first. I'm not sure what the logic behind the decision to do that was. I'd ask Stef about it.

**Comment by minerscale** [comment]
Oooh, ok. Well, that seems a bit strange. It doesn't matter anyway. Do I close it now?

**Comment by kubilus1** [comment]
Yeah, I think we will close it since it is an SGDK, not exactly issue, but behavior.
