### ISSUE TITLE
Update SGDK

### ISSUE THREAD

**Issue by skarab** [kubilus1/gendev#36]
Awesome project, but the SGDK is outdated, possible to update it to latest version please ?

**Comment by emeric-martineau** [comment]
Hi,

I just make a Pull Request #42 to update SGDK 1.40.

If it's work fine for you, please add :+1: on PR.

Regards,

**Comment by kivutar** [comment]
Hello could somebody update gendev to SGDK 1.41? It fixes important bugs. https://github.com/Stephane-D/SGDK/releases/tag/v1.41

**Comment by kubilus1** [comment]
Sounds good, build is happening right-now.

**Comment by valdirSalgueiro** [comment]
1.5 is out, it would be nice if gendev is updated or how could I update myself? thanks!
