### ISSUE TITLE
Float support

### ISSUE THREAD

**Issue by skarab** [kubilus1/gendev#38]
Hello,
I'm trying to convert old windows code to gendev, I'm using FIX16 and I got this :
main.c:(.text+0x432): undefined reference to `__floatsisf'
main.c:(.text+0x440): undefined reference to `__mulsf3'
main.c:(.text+0x450): undefined reference to `__addsf3'
main.c:(.text+0x460): undefined reference to `__mulsf3'
main.c:(.text+0x46a): undefined reference to `__fixsfsi'
Is there something I can do to fix it ?
Thanks.

**Comment by andwn** [comment]
The MegaDrive doesn't have an FPU, so using floating point is not possible.

The solution would be to replace all floating point logic with fixed point. I see you mentioned FIX16 but nobody can say exactly where the issue in the code is without seeing it.

**Comment by skarab** [comment]
FIX16(12.0f) works with sgdk on windows, not on gendev.

**Comment by skarab** [comment]
Ok, I achieved to port my old demo effects without problems, float support isn't an issue.
Thanks.
