### ISSUE TITLE
make issues.

### ISSUE THREAD

**Issue by nabulator** [kubilus1/gendev#5]
Ubuntu 14.04 make is having problems finding a file. (this is my second time running it)

> cd work/sjasm && \
>     unzip ../sjasm39g6.zip && \
>     cd sjasmsrc39g6 && \
>     make && \
>     cp sjasm /opt/toolchains/gen/bin/sjasm && \
>     chmod +x /opt/toolchains/gen/bin/sjasm
> Archive:  ../sjasm39g6.zip
>   End-of-central-directory signature not found.  Either this file is not
>   a zipfile, or it constitutes one disk of a multi-part archive.  In the
>   latter case the central directory and zipfile comment will be found on
>   the last disk(s) of this archive.
> unzip:  cannot find zipfile directory in one of ../sjasm39g6.zip or
>         ../sjasm39g6.zip.zip, and cannot find ../sjasm39g6.zip.ZIP, period.
> make: **\* [/opt/toolchains/gen/bin/sjasm] Error 9

**Comment by hansbonini** [comment]
Same problem...
to solve this, i downloaded sjasm from here 
https://github.com/samsaga2/sjasm

and make separetely

after this comment sjasm entries on makefile

**Comment by nevat** [comment]
Same problem, with another file: bin2c

bin2c-1.0.zip                                               100%[==========================================================================================================================================>]     639  --.-KB/s   in 0s     

2015-07-18 00:48:15 (239 MB/s) - ‘bin2c-1.0.zip’ saved [639/639]

cd work && \
unzip bin2c-1.0.zip && \
cd bin2c && \
gcc bin2c.c -o bin2c && \
cp bin2c /opt/toolchains/gen/bin/bin2c 
Archive:  bin2c-1.0.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of bin2c-1.0.zip or
        bin2c-1.0.zip.zip, and cannot find bin2c-1.0.zip.ZIP, period.
Makefile:214: recipe for target '/opt/toolchains/gen/bin/bin2c' failed
make: **\* [/opt/toolchains/gen/bin/bin2c] Error 9

**Comment by kubilus1** [comment]
Apparently sourceforge is having issues.  When I look at the bin2c zip file I download this is what it shows:

<html><head>
<title>SourceForge</title>



<script src="//code.jquery.com/jquery-1.11.0.min.js"></script>

<script src="//sourceforge.net/js/mirrors.js"></script>

<script src="/js/sf.js"></script>

<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'http://sourceforge.net/home.html';
}
</script>

</head><body>

<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.
</noscript>

</body></html>

**Comment by kubilus1** [comment]
I will look at finding some way to host these build requirements elsewhere.  Not sure if there is enough room on this github project for all of them.  (maybe just the problematic ones!)

**Comment by kubilus1** [comment]
Okay I pushed all the build requirements into the source tree.  The will hopefully keep things working smoother.
