### ISSUE TITLE
None of the Examples or Samples compile

### ISSUE THREAD

**Issue by dleslie** [kubilus1/gendev#52]
I built the Docker image which executes the makefile.gen as described in the Readme, and it does not seem to be capable of compiling any of gendev's examples nor any of SGDK's samples.

```
:dleslie:pinebookpro [sprite] 
#> alias make-gendev
alias make-gendev='docker container run --rm --name gendev'
:dleslie:pinebookpro [sprite] 
#> make-gendev 
mkdir -p src/boot
mkdir -p out
mkdir -p out/src
mkdir -p out/res
cp /opt/gendev/sgdk/src/boot/sega.s src/boot/sega.s
cp /opt/gendev/sgdk/src/boot/rom_head.c src/boot/rom_head.c
/opt/gendev/bin/m68k-elf-gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -fno-builtin -Iinc -Isrc -Ires -I/opt/gendev/sgdk/inc -I/opt/gendev/sgdk/res -B/opt/gendev/sgdk/bin -c src/boot/rom_head.c -o out/rom_head.o
/opt/gendev/bin/m68k-elf-ld -T /opt/gendev/sgdk/md.ld -nostdlib --oformat binary -o out/rom_head.bin out/rom_head.o
/opt/gendev/bin/m68k-elf-gcc -m68000 -Wall -Wextra -Wno-shift-negative-value -fno-builtin -Iinc -Isrc -Ires -I/opt/gendev/sgdk/inc -I/opt/gendev/sgdk/res -B/opt/gendev/sgdk/bin -c src/boot/sega.s -o out/sega.o
echo "" > out/cmd_
/opt/gendev/bin/m68k-elf-gcc -B/opt/gendev/sgdk/bin -n -T /opt/gendev/sgdk/md.ld -nostdlib out/sega.o @out/cmd_ /opt/gendev/sgdk/lib/libmd.a /opt/gendev/sgdk/lib/libgcc.a -o out/rom.out
/opt/gendev/sgdk/lib/libmd.a(sys.o): In function `_start_entry':
sys.c:(.text+0x8a4): undefined reference to `main'
/opt/gendev/sgdk/lib/libmd.a(sys.o): In function `_reset_entry':
sys.c:(.text+0x8e2): undefined reference to `main'
collect2: error: ld returned 1 exit status
/opt/gendev/sgdk/mkfiles/makefile.gen:122: recipe for target 'out/rom.out' failed
make: *** [out/rom.out] Error 1
```

It looks like it's not compiling anything other than the rom header and sega structures.

----

**Edit**: I've corrected the build command and wrote a script to iterate through all the examples to attempt to build them. It seems like they still fail to build, but for several reasons.

The output is here:
https://gist.github.com/dleslie/80a59ee3fd278524fce252d7c9645683

And the repo I use for building the examples is here:
https://github.com/dleslie/genesis-dev/tree/master/examples/gendev

**Errors**

```
main.c:181:21: error: 'PLAN_A' undeclared (first use in this function)
     BMP_init(FALSE, PLAN_A, FALSE, 0);
```

Both 3d examples fail with the above. PLAN_A was renamed in SGDK to BG_A, I think?

```
nm --plugin=liblto_plugin-0.dll -n out/rom.out > out/symbol.txt
nm: liblto_plugin-0.dll: cannot open shared object file: No such file or directory
```

I think something critical is missing from the Dockerfile? Most of the examples fail with this one.

**Comment by kubilus1** [comment]
I don't see that you are mounting any source code, so I would expect this
to fail.  Key error 'sys.c:(.text+0x8e2): undefined reference to `main''

**Comment by dleslie** [comment]
Ah crap, I missed that. Thanks @kubilus1

**Comment by kubilus1** [comment]
No problem!  Happy coding!

**Comment by dleslie** [comment]
@kubilus1 I'm having issues still, and updated the description. Things are compiling, but I think changes in SGDK broke some examples, and something is misconfigured with the Dockerfile.

**Comment by kubilus1** [comment]
So that second part with the 'nm' thing is just a warning I believe.  I noticed that and updated the repo about it to clear that up.

As far as my old 3d examples, yeah they likely are not 100% compatible with the latest version of SGDK.  SGDK unfortunately does not keep a very stable API :/  

The samples _within_ SGDK should all compile though (I have CICD tests on these).

**Comment by dleslie** [comment]
The `nm` thing is preventing the creation of `symbol.txt`, which I imagine is useful for debugging.
