### ISSUE TITLE
Wishlist: parallel make

### ISSUE THREAD

**Issue by clbr** [kubilus1/gendev#9]
It would be nice to have the build be parallel. Currently even the setup target fails with parallel make, and it's a bit unconventional nowadays to require a serial build, with all these cores ;)

**Comment by kubilus1** [comment]
I actually looked into just this.  I believe there was some issue when compiling binutils.  I agree this would be nice to have.

**Comment by kubilus1** [comment]
Attempted this in a number of ways and could not get a successful build.  I will accept patches that make this work but likely won't spend any more time myself on it.
